version: "2"

services:
  prometheus:
    image: gesellix/prometheus:armv7
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - prom
    volumes:
      - ./prometheus/prometheus.yml:/prometheus/prometheus.yml

  alertmanager:
    image: gesellix/alertmanager:armv7
    container_name: alertmanager
    ports:
      - "9093:9093"
    networks:
      - prom
    volumes:
      - ./alertmanager/alertmanager.yml:/alertmanager/alertmanager.yml

  node_exporter:
    image: gesellix/node-exporter:armv7
    container_name: node
    ports:
      - "9100:9100"
    networks:
      - prom

networks:
  prom:

