version: "2"

services:
  prometheus:
    image: gesellix/prometheus:armv7
    command: ./prometheus -alertmanager.url=http://alertmanager:9093
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - prom
    volumes:
      - ./prometheus/prometheus.yml:/prometheus/prometheus.yml
      - ./prometheus/alerts.rules:/prometheus/alerts.rules

  alertmanager:
    image: gesellix/alertmanager:armv7
    container_name: alertmanager
    ports:
      - "9093:9093"
    networks:
      - prom
    volumes:
      - ./alertmanager/alertmanager.yml:/alertmanager/alertmanager.yml

  node_exporter:
    image: gesellix/node-exporter:armv7
    command: ./node_exporter -collector.procfs /host/proc -collector.sysfs /host/proc -collector.filesystem.ignored-mount-points "^/(sys|proc|dev|host|etc)($$|/)" -collectors.enabled conntrack,diskstats,entropy,filefd,filesystem,loadavg,mdadm,meminfo,netdev,netstat,sockstat,stat,textfile,time,uname,vmstat
    container_name: node
    ports:
      - "9100:9100"
    networks:
      - prom
    volumes:
      - /proc:/host/proc
      - /sys:/host/sys
      - /:/rootfs

networks:
  prom:

